[iris]
LogLevel = "debug"
SocketSharding = true
DisableStartupLog= false
FireMethodNotAllowed= true
ForceLowercaseRouting= true
TimeFormat= "2006-01-02 15:04:05"
DisableBodyConsumptionOnUnmarshal= true
FireEmptyFormError= true
PostMaxMemory= 67108864
RemoteAddrHeaders= ["X-Real-Ip", "X-Forwarded-For", "CF-Connecting-IP", "True-Client-Ip"]
[http]
# 运行模式
debug = true
# 是否开启健康检查
health = true
# http 绑定地址
bind-address = "0.0.0.0"
#  http 绑定端口
bind-port = 8091
# 启用的中间件
middlewares = ["logger", "cors"]
# https 配置
cert-file = ""
# 是否启用性能分析
enable-profiling = true
# 是否启用监控
enable-metrics = false

[log]
# 日志输出路径
output-paths = ["stderr"]
# 日志级别
level = "INFO"
# 日志输出格式 json 和 console
format = "console"
# 是否禁用输出行号
disable-caller = false
# 是否禁用输出错误堆栈
disable-stacktrace = true
# 是否禁用颜色输出
enable-color = true
# 是否禁用开发模式
development = true
# 日志标签名
name = ""

[jwt]
# 密钥
key = "secret key"
# 访问令牌过期时间(分)
access-expire = 15
# 刷新令牌过期时间(小时)
refresh-expire = 24
# 随机盐，长度必须是 16 24 32
salt = "BgCA87jH2xrN2z3X"